// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_EasingPicture","status":true,"description":"イージングピクチャ ver1.1.0\r\nピクチャ毎のモーション毎にイージングを設定","parameters":{}},
{"name":"Tween","status":true,"description":"","parameters":{}}
];
